- name: creating EC2 & Route53 using playbook
  hosts: localhost
  connection: local

  vars:
    sg_id: sg-01a477711f7deba28
    instances:
      - name: centos
        ami_id: ami-09c813fb71547fc4f
      - name: ubuntu
        ami_id: ami-0360c520857e3138f  

  tasks:
    - name: create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ item.ami_id }}"
        tags:
          Name: "{{ item.name }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: print EC2 output
      ansible.builtin.debug:
        var: ec2_output
